try {
  const aa = 0;
  aa = 904;
} catch (error) {
  console.log(error.message);
}
